import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/shared/sidebar";
import { Stack } from "@chakra-ui/react";
import { Header } from "@/components/shared/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Stack
            flexDir={"row"}
            gap={0}
            bg={{ _light: "#F7F7F7", _dark: "black" }}
          >
            <SideBar />
            <Stack flex={1}>
              <Header />
              <Stack px={16} py={8}>
                {children}
              </Stack>
            </Stack>
          </Stack>
        </Provider>
      </body>
    </html>
  );
}
